parameters:
    twilio_sid: ACcd4574347e8dfd1a7ebbd37565556839
    twilio_token: 43017094762e38df6cd2327c4963796e
    twilio_number: '+18634174577'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    sensio_framework_extra.view.listener:
        alias: Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener

    Twilio\Rest\Client:
        autowire: true
        arguments: ['%twilio_sid%', '%twilio_token%']